// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
    /** Headline */
    title: string;

    /** Parent page */
    parentPage?: IArticle | IPage | undefined;

    /** Article introduction */
    shortDescription?: string | undefined;

    /** Article content */
    content: string;

    /** Image */
    image?: Asset | undefined;

    /** Related content */
    related?: (IArticle | IPage)[] | undefined;

    /** Tags */
    tags?: ITag[] | undefined;

    /** Article meta data */
    metaData?: IMetaData | undefined;

    /** Slug */
    name: string;
}

/** Articles; such as news, blog posts, press releases */

export interface IArticle extends Entry<IArticleFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "article";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface ICtaFields {
    /** Content name */
    name?: string | undefined;

    /** Button text */
    title: string;

    /** Page link */
    pageReference?: IPage | undefined;

    /** External URL */
    href?: string | undefined;

    /** Open link in new browser tab */
    target?: "Yes"[] | undefined;
}

/** A textfield combined with a URL */

export interface ICta extends Entry<ICtaFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "cta";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IFooterFields {
    /** Content name */
    name: string;

    /** Main footer navigation */
    navigation?: INavigation | undefined;

    /** Copyright message */
    copyright?: string | undefined;
}

/** A grouping of content which sits at the bottom of a page. */

export interface IFooter extends Entry<IFooterFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "footer";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IHeaderFields {
    /** Content name */
    name: string;

    /** Logo */
    logo?: Asset | undefined;

    /** Logo Link */
    linkReference?: IPage | undefined;

    /** Header navigation */
    navigation?: INavigation | undefined;
}

/** A component that contains content that will appear in a header section */

export interface IHeader extends Entry<IHeaderFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "header";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IImageFields {
    /** Content name */
    name: string;

    /** image */
    image: Asset;
}

/** A content wrapper for Images */

export interface IImage extends Entry<IImageFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "image";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IListFields {
    /** Content name */
    name: string;

    /** Search query */
    queryJSON?: Record<string, any> | undefined;

    /** Content items */
    consys?: (IArticle | IPage | IVideo)[] | undefined;
}

/** A wrapper component for listing content.  e.g Articles.
Has functionality to query and display content based on a search query. e.g. Latest 10 Articles */

export interface IList extends Entry<IListFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "list";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IMetaDataFields {
    /** Content name */
    name: string;

    /** Browser title */
    browserTitle?: string | undefined;

    /** Page description */
    pageDescription?: string | undefined;

    /** Facebook OG title */
    ogTitle?: string | undefined;

    /** Facebook OG description */
    ogDescription?: string | undefined;

    /** Facebook OG image */
    ogImage?: Asset | undefined;

    /** Twitter title */
    twitterTitle?: string | undefined;

    /** Twitter description */
    twitterDescription?: string | undefined;

    /** Twitter image */
    twitterImage?: Asset | undefined;

    /** Robots no index */
    robotsNoIndex?: "NOINDEX"[] | undefined;

    /** Robots no follow */
    robotsNoFollow?: "NOFOLLOW"[] | undefined;

    /** Change frequency */
    changeFrequency?:
        | "always"
        | "hourly"
        | "daily"
        | "weekly"
        | "monthly"
        | "yearly"
        | "never"
        | undefined;

    /** Priority */
    priority?:
        | "1.0"
        | "0.9"
        | "0.8"
        | "0.7"
        | "0.6"
        | "0.5"
        | "0.4"
        | "0.3"
        | "0.2"
        | "0.1"
        | "0.0"
        | undefined;
}

/** Holds meta data for a page including Page description and social meta descriptions */

export interface IMetaData extends Entry<IMetaDataFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "meta-data";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface INavigationFields {
    /** Content name */
    name: string;

    /** Pages to appear in this navigation */
    pages?: IPage[] | undefined;
}

/** A Navigation item containing references to pages.
Typically used for Main/Footer navigations. */

export interface INavigation extends Entry<INavigationFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "navigation";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IPageFields {
    /** Page name */
    title: string;

    /** Parent page */
    parentPage?: IArticle | IPage | undefined;

    /** Content on this page */
    consys?:
        | (
              | IArticle
              | ICta
              | IFooter
              | IHeader
              | IImage
              | IList
              | IMultipleColumn
              | INavigation
              | IRichText
              | IVideo
          )[]
        | undefined;

    /** Link to external page */
    url?: string | undefined;

    /** Page meta data */
    metaData?: IMetaData | undefined;

    /** Page image */
    image?: Asset | undefined;

    /** Tags */
    tags?: ITag[] | undefined;

    /** Page slug */
    name: string;
}

/** A page identifier.  Use this to build a webpage of content that can appear in site navigations. */

export interface IPage extends Entry<IPageFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "page";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IRedirectFields {
    /** Content name */
    name: string;

    /** URL from */
    source: string;

    /** Redirect to */
    destination?: IArticle | IPage | undefined;

    /** Redirect to URL */
    destinationExplicit?: string | undefined;
}

/** Add redirects for vanity URLs, legacy redirects and SEO */

export interface IRedirect extends Entry<IRedirectFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "redirect";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IRichTextFields {
    /** Content name */
    name?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Button */
    cta?: ICta | undefined;
}

/** A Rich text component with Markdown Editor */

export interface IRichText extends Entry<IRichTextFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "rich-text";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface ITagFields {
    /** Tag title */
    title: string;

    /** Tag slug */
    name: string;
}

/** A basic data type for a content tag */

export interface ITag extends Entry<ITagFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "tag";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export interface IVideoFields {
    /** Video title */
    title: string;

    /** Video asset */
    video?: Asset | undefined;

    /** Video image */
    poster?: Asset | undefined;

    /** Autoplay */
    autoplay?: boolean | undefined;

    /** Loop */
    loop?: boolean | undefined;

    /** Display video controls */
    controls?: boolean | undefined;

    /** Description */
    description?: string | undefined;

    /** Display titles and descriptions */
    displayTitles?: "yes"[] | undefined;
}

/** A component that displays a video. Can have optional elements like strapline, heading, description. Optional viewport transition. */

export interface IVideo extends Entry<IVideoFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "video";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

type CONTENT_TYPE =
    | "article"
    | "cta"
    | "footer"
    | "header"
    | "image"
    | "list"
    | "meta-data"
    | "navigation"
    | "page"
    | "redirect"
    | "rich-text"
    | "tag"
    | "video";

type LOCALE_CODE = "en-US";

type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
